class TenancyHelper
  DEFAULT_STATISTICS_RESPONSE = {
    "items": [
      { "area": "Bayview West",
        "dwell": "Flat",
        "nBedrms": "1",
        "nLodged": 6,
        "nClosed": 6,
        "nCurr": nil,
        "mean": 543,
        "lq": 463,
        "med": nil,
        "uq": nil,
        "sd": 181,
        "brr": nil,
        "lmean": nil,
        "lsd": nil,
        "slq": nil,
        "suq": nil, },
      { "area": "Bayview West",
        "dwell": "House",
        "nBedrms": "3",
        "nLodged": 30,
        "nClosed": 33,
        "nCurr": nil,
        "mean": 671,
        "lq": 650,
        "med": nil,
        "uq": nil,
        "sd": 45,
        "brr": nil,
        "lmean": nil,
        "lsd": nil,
        "slq": nil,
        "suq": nil, },
    ], "periodCovered": "2023-5-1/2024-12-31", "areaDefinition": "SAU2019",
  }.freeze
end
